on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-lates
    steps:
    - name: Install Chrome
      run: |
        CHROME_VERSION="117.0.5938.92-1"
        wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${CHROME_VERSION}_amd64.deb
        sudo dpkg -i google-chrome-stable_${CHROME_VERSION}_amd64.deb
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - run: yarn install
    - run: yarn add pa11y
    - run: pa11y https://pa11y.org/
