on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Lint and test on ${{ matrix.os }} with Node.js ${{ matrix.node-version }} 
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node-version: [20]
    steps:
      - name: Normalise line-ending handling in Git
        shell: bash
        run: |
          git config --global core.autocrlf false
        if: runner.os == 'Windows'
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn add pa11y
      - run: pa11y https://pa11y.org/
